/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnicourse_hhx_com_jnidemo_StaticTest */

#ifndef _Included_jnicourse_hhx_com_jnidemo_StaticTest
#define _Included_jnicourse_hhx_com_jnidemo_StaticTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnicourse_hhx_com_jnidemo_StaticTest
 * Method:    doAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jnicourse_hhx_com_jnidemo_StaticTest_doAdd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
