/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <cstddef>
/* Header for class jnicourse_hhx_com_jnidemo_DynamicTest */

#ifndef _Included_jnicourse_hhx_com_jnidemo_DynamicTest
#define _Included_jnicourse_hhx_com_jnidemo_DynamicTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnicourse_hhx_com_jnidemo_DynamicTest
 * Method:    doTwo
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL addTwoNumber
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
